# Generated by Django 4.2.23 on 2025-11-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='Trading League', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeagueParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wins', models.CharField(blank=True, max_length=100, null=True)),
                ('losses', models.CharField(blank=True, max_length=100, null=True)),
                ('isLeagueAdmin', models.BooleanField(null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='catalog.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('league', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLeagueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_start_of_week', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shares', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('league_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.leagueparticipant')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('start_of_week_net_worth1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_of_week_net_worth2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='catalog.league')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_p1', to='catalog.leagueparticipant')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_p2', to='catalog.leagueparticipant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchup_wins', to='catalog.leagueparticipant')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('league', 'week_number', 'participant1', 'participant2')},
            },
        ),
    ]
