# Generated by Django 4.2.23 on 2025-11-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueparticipant',
            name='isLeagueAdmin',
        ),
        migrations.AddField(
            model_name='leagueparticipant',
            name='leagueAdmin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
