# Generated by Django 4.2.23 on 2025-11-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_leagueparticipant_isleagueadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueparticipant',
            name='leagueAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
