# Generated by Django 4.2.23 on 2025-11-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_leagueparticipant_leagueadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
