# Generated by Django 4.2.23 on 2025-12-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_last_api_call_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matchup',
        ),
    ]
