# Generated by Django 4.2.23 on 2025-12-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_api_call_tracker'),
        ('catalog', '0007_delete_matchup'),
    ]

    operations = [
    ]
