# Generated by Django 4.2.23 on 2025-12-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_day_start_price_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='start_price',
            field=models.DecimalField(decimal_places=2, help_text="Yesterday's closing price (updated daily)", max_digits=10),
        ),
    ]
